### ISSUE TITLE
bug when eigen vector is [0,1]

### ISSUE THREAD

**Issue by JaySlamer** [derekharrison/eigen-decomposition#1]
when eigen vector is [0,1],  for example when estimate the direction of a horizontal line using its discrete samples, the result would be nan. I realized there is a problem with VectorNormalization function so I added a very small positive number to sqrt(sqrtwpwp) to avoid divided by zero. However, the result would become [0,0], not [0,1]. Using SelfAdjointEigenSolver from eigen library would get the right answer [0,1]

**Comment by derekharrison** [comment]
Can you provide the input you used which gave incorrect results? I fed the algorithm the matrix [[x, 0][0, y]] which has eigenvectors [0,1] and [1,0] and the vectors were correctly computed, so I was unable to find a case which fails. And thanks for noting the potential division by zero when normalising.
